### ISSUE TITLE
请求增加调整屏幕通知的设置

### ISSUE THREAD

**Issue by panhongtao07** [developer-ken/MouseSwitcher#3]
用户对于弹出通知可能各有偏好，希望能支持对每次切换时通知的自定义设置，重要性依序降低：
1. 选择是否弹出通知（显示当前显示器号）。禁用该设置可能更便于实现隐藏后台程序(#2 )。
2. 选择弹出通知的位置。例如，与系统的显示器编号“检测”功能统一，显示在屏幕左下角，或者在其它角落等。
3. 可能的其他设置，如显示窗口大小，显示时间等。

**Comment by developer-ken** [comment]
功能1、2已经实现，功能3并不紧急，将不会立即跟进
