### ISSUE TITLE
快捷键不支持许多常用设置和禁用快捷键

### ISSUE THREAD

**Issue by panhongtao07** [developer-ken/MouseSwitcher#4]
- 快捷键必须绑定到特定触发键（如Alt），常用软件通常为每个功能单独设置完整触发路径（如Alt+1）而非两步设置。
- 快捷键不能设置复杂触发路径，如Alt+Ctrl+1中，以现在的设置为触发键Alt和快捷键Ctrl+1或反过来，但尚不支持此类设置。
- 快捷键无法禁用：双屏时上一屏和下一屏有相同功能，但必须设置不同的快捷键。应能支持禁用其中一个。
- 保存的逻辑不清晰：在关闭设置窗口时触发，而非提供保存按钮，在保存时触发。目前似乎没有错误修改后禁止保存的方法。

**Comment by developer-ken** [comment]
分别设置触发键、复杂触发路径、保存逻辑涉及到对快捷键系统的较大更改，暂时不会跟进；
禁用快捷键功能已经实现。

**Comment by panhongtao07** [comment]
感谢关注和回复。复杂改动的如果不方便不用太在意，能及时改进已经很好了！
